### ISSUE TITLE
[Bug] 1.20.6 | List Formatting not working. - LuckPerms

### ISSUE THREAD

**Issue by CaptnLucid** [nulli0n/nightcore-spigot#14]
List formatting doesn't seem to be working appropriately when it comes to detecting ranks. I have LuckPerms installed and have changed my user's rank to the 3 different ones available.

```yaml
List:
    owner:
      Priority: 10
      Name: "%rank_owner%%player_info%: "
      Message: "%msg%"
      Ranks:
        - owner
        - admin
    admin:
      Priority: 9
      Name: "%user_tag%%rank_member%%user_admin% &8» "
      Message: "%msg%"
      Ranks:
        - admin
    default:
      Priority: 0
      Name: "%user_tag%%rank_member%%user_default% &8» "
      Message: "%msg%"
      Ranks:
        - "*"
```

The `default` takes priority. If i change the group to `default` instead of `'*'`, I receive this as an error.

`[18:54:56 ERROR]: [SunLight] [Chat] Could not handle message from 'LucidiousXIV': No format is available!`

The formatting only applies if the ranks have the `'*'` field

Loading the prefix from LuckPerms works perfectly fine, so it seems to be an issue with pulling the rank itself.

Edit: Loading the prefix via LuckPerms is via the LuckPerms Placeholder, not the Vault Placeholder. Felt as I should be clear about that. Also have the same thing reported over at Sunlight though I feel it's more suited here due to nightcore handling the group checking via Vault from here.

**Comment by CaptnLucid** [comment]
@nulli0n 
![image](https://github.com/user-attachments/assets/22dc8158-efdc-4274-ad39-5f8c3db73847)
and
![image](https://github.com/user-attachments/assets/4d001081-5c24-4523-b48c-70e672fed000)
and
![image](https://github.com/user-attachments/assets/aef670f8-c084-4efe-abcf-61392263ea27)

I'm unsure what you mean by "display" option, unless you're referring to the displayname, which I do have set to Admin, however nightcore isn't recognizing it.

```yaml
  List:
    admin:
      Priority: 10
      Name: "%user_tag%%rank_member%%user_admin% &8» "
      Message: "%msg%"
      Ranks:
        - Admin
    donor_rank1:
      Priority: 0
      Name: "%user_tag%%rank_member%%user_default% &8» "
      Message: "%msg%"
      Ranks:
        - donor_rank1
    default:
      Priority: 0
      Name: "%user_tag%%rank_member%%user_default% &8» "
      Message: "%msg%"
      Ranks:
        - default
```
