### ISSUE TITLE
Spin sound not working

### ISSUE THREAD

**Issue by Truongvv10** [nulli0n/nightcore-spigot#28]
```yml
Settings:
  # GUI title.
  Title: <black>Opening %crate_name%</black>
  # GUI size. Must be multiply of 9.
  # Useful for 'CHEST' Inventory Type only.
  Size: 45
  # GUI type.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryType.html
  Inventory_Type: CHEST
  # Sets GUI auto-refresh interval (in seconds). Set this to 0 to disable.
  Auto_Refresh: 0
  Mode: NORMAL
  WinSlots: 22
  ScriptRunner:
    OnOpen:
    - '[run_reward] id:"dummy" name:"dummy_1" delay:"0" slots:"0,9,18,27,36,8,17,26,35,44" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_1" delay:"7"'
    - '[run_animation] id:"fill_black" name:"fill_1" delay:"7" slots:"0,9,18,27,36,8,17,26,35,44" mode:"syncrhonized" chance:"100"'
    - '[play_sound] name:"entity_generic_explode" delay:"7"'
    - ''
    - '[run_reward] id:"dummy" name:"dummy_2" delay:"0" slots:"1,10,19,28,37,7,16,25,34,43" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_2" delay:"14"'
    - '[run_animation] id:"fill_black" name:"fill_2" delay:"14" slots:"1,10,19,28,37,7,16,25,34,43" mode:"syncrhonized" chance:"100"'
    - '[play_sound] name:"entity_generic_explode" delay:"14"'
    - ''
    - '[run_reward] id:"dummy" name:"dummy_3" delay:"0" slots:"2,11,20,29,38,6,15,24,33,42" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_3" delay:"21"'
    - '[run_animation] id:"fill_gray" name:"fill_3" delay:"21" slots:"2,11,20,29,38,6,15,24,33,42" mode:"syncrhonized" chance:"100"'
    - '[play_sound] name:"entity_generic_explode" delay:"21"'
    - ''
    - '[run_reward] id:"dummy" name:"dummy_4" delay:"0" slots:"3,5,39,41" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_4" delay:"28"'
    - '[run_animation] id:"fill_gray" name:"fill_4" delay:"28" slots:"3,5,39,41" mode:"syncrhonized" chance:"100"'
    - ''
    - '[run_reward] id:"dummy" name:"dummy_5" delay:"0" slots:"4,40" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_5" delay:"35"'
    - '[run_animation] id:"fill_gray" name:"fill_5" delay:"35" slots:"4,40" mode:"syncrhonized" chance:"100"'
    - ''
    - '[run_reward] id:"dummy" name:"dummy_6" delay:"0" slots:"12,21,30,14,23,32" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_6" delay:"42"'
    - '[run_animation] id:"fill_white" name:"fill_6" delay:"42" slots:"12,21,30,14,23,32" mode:"syncrhonized" chance:"100"'
    - ''
    - '[run_reward] id:"dummy" name:"dummy_7" delay:"0" slots:"13,31" mode:"independent" chance:"100.0"'
    - '[stop_reward] name:"dummy_7" delay:"49"'
    - '[run_animation] id:"fill_white" name:"fill_7" delay:"49" slots:"13,31" mode:"syncrhonized" chance:"100"'
    - ''
    - '[run_reward] id:"default" name:"real" delay:"0" slots:"22" mode:"independent" chance:"100.0"'
    - '[play_sound] name:"entity_generic_explode" delay:"50"'
    OnStart: []
  Selection:
    Amount: 1
    SelectedIcon:
      Material: ENDER_CHEST
    AutoRun: false
  # Sets max. amount of the opening ticks while players can skip the opening animation.
  # Set to -1 to disable (no skip).
  Max_Ticks_To_Skip: 40
  PlaceholderAPI:
    # Sets whether PlaceholderAPI placeholders will be applied on all items from the 'Content' section of this GUI.
    # [*] Disable if you don't use any PlaceholderAPI placeholders on your items to improve GUI performance.
    Enabled: false
# ==================== GUI CONTENT ====================
# You can freely edit items in this section as you wish (add, remove, modify items).
# The following values are available as button Types:
# CLOSE
# SELECT
# START
# ==================== ITEM OPTIONS ====================
# > Item: Item to display. Please check: https://github.com/nulli0n/nightcore-spigot/wiki/ItemStack-Options
# > Priority: Button priority. Better values will override other item(s) in the same slot(s).
# > Slots: Button slots. From [0] to [Size - 1]. Split with commas.
# > Click_Commands: Execute custom commands on click. PlaceholderAPI available here.
#     Available click types: LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, DROP_KEY, SWAP_KEY, NUMBER_1, NUMBER_2, NUMBER_3, NUMBER_4, NUMBER_5, NUMBER_6, NUMBER_7, NUMBER_8, NUMBER_9
#     Use prefix 'player:' to run command by a player.
#     Click_Commands:
#       LEFT:
#       - say Hello
#       - give %player_name% diamond 1
#       - player: menu open shops
# ==================================================
Content: {}

Rewards:
  default:
    Rarities:
    - '*'
    Spin_Times: 25
    Spin_Interval: 2
    Spin_Slowdown:
      Step: 0
      Amount: 0
    Spin_Sound:
      # Sound volume. From 0.0 to 1.0.
      Volume: 0.5
      # Sound speed. From 0.5 to 2.0
      Pitch: 1.0
      # Sound name. You can use Spigot sound names, or ones from your resource pack.
      # Spigot Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      Name: BLOCK_NOTE_BLOCK_XYLOPHONE
  
  dummy:
    Rarities:
    - '*'
    Spin_Times: -1
    Spin_Interval: 2
    Spin_Slowdown:
      Step: 0
      Amount: 0

Animations:
  fill_black:
    Spin_Times: 1
    Spin_Interval: 1
    Spin_Slowdown:
      Step: 0
      Amount: 0
    Spin_Sound:
      # Sound name. You can use Spigot sound names, or ones from your resource pack.
      # Spigot Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      Name: BLOCK_PISTON_EXTEND
      # Sound volume. From 0.0 to 1.0.
      Volume: 1.0
      # Sound speed. From 0.5 to 2.0
      Pitch: 1.0
    Items:
      pane:
        Chance: 100.0
        Material: BLACK_STAINED_GLASS_PANE
  
  fill_gray:
    Spin_Times: 1
    Spin_Interval: 1
    Spin_Slowdown:
      Step: 0
      Amount: 0
    Spin_Sound:
      # Sound name. You can use Spigot sound names, or ones from your resource pack.
      # Spigot Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      Name: BLOCK_PISTON_EXTEND
      # Sound volume. From 0.0 to 1.0.
      Volume: 1.0
      # Sound speed. From 0.5 to 2.0
      Pitch: 1.0
    Items:
      pane:
        Chance: 100.0
        Material: GRAY_STAINED_GLASS_PANE
  
  fill_white:
    Spin_Times: 1
    Spin_Interval: 1
    Spin_Slowdown:
      Step: 0
      Amount: 0
    Spin_Sound:
      # Sound name. You can use Spigot sound names, or ones from your resource pack.
      # Spigot Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      Name: BLOCK_PISTON_EXTEND
      # Sound volume. From 0.0 to 1.0.
      Volume: 1.0
      # Sound speed. From 0.5 to 2.0
      Pitch: 1.0
    Items:
      pane:
        Chance: 100.0
        Material: WHITE_STAINED_GLASS_PANE

```
