### ISSUE TITLE
Locale not working

### ISSUE THREAD

**Issue by vtwsu** [nulli0n/nightcore-spigot#50]
Hello!
I would like to get support for the usual number formats, except through ","

Current configuration settings:
```
  Format:
    Format: '#,###.##'
    Rounding: HALF_EVEN
    Locale: ru_RU
```
Expected result: 1,000,000
Actual result: 1,000,000

In this form, the locale does not work and does not display spaces, the default output remains comma-separated.

***

Здравствуйте!
Хотелось бы получить поддержку привычных форматов чисел, кроме как через ","

Текущие настройки конфигурации:
```
  Format:
    Format: '#,###.##'
    Rounding: HALF_EVEN
    Locale: ru_RU
```
Ожидаемый результат: 1 000 000
Реальный результат: 1,000,000

В таком виде локаль не работает и не отображает пробелы, остается вывод по умолчанию через запятую.

**Comment by nulli0n** [comment]
This works fine for me
```yaml
  Format:
    Format: '#,###.###'
    Rounding: half_even
    Locale: fr-FR
```
